.. _SublimeLinter: https://github.com/SublimeLinter/SublimeLinter3
.. _Sublime Text 3: http://www.sublimetext.com/3
.. _Package Control: https://sublime.wbond.net/installation
.. _flake8: http://flake8.readthedocs.org/en/latest/
.. _jshint: http://jshint.org/docs/
.. _node: http://nodejs.org
.. _csslint: https://github.com/stubbornella/csslint/wiki/About
.. _rbenv: https://github.com/sstephenson/rbenv
.. _easy_install: https://pypi.python.org/pypi/setuptools
.. _pip: http://pip.readthedocs.org/en/latest/
.. _python regular expression: http://docs.python.org/3/library/re.html#regular-expression-syntax

.. |sl| replace:: SublimeLinter
.. |st| replace:: Sublime Text 3
.. |pc| replace:: Package Control
.. |cmd| replace:: Command Palette (:kbd:`cmd+shift+p` on Mac OS X, :kbd:`ctrl+shift+p` on Linux/Windows)
.. |path| replace:: ``PATH``
.. |re-try| replace:: If you need help constructing a regular expression, the `re-try <http://re-try.appspot.com>`__ site provides an easy way to test out your regular expressions. Be sure to uncheck the “options” checkboxes.

.. |_sl| replace:: `SublimeLinter <https://github.com/SublimeLinter/SublimeLinter3>`__
.. |_org| replace:: `SublimeLinter organization <https://github.com/SublimeLinter>`__
.. |_st| replace:: `Sublime Text 3 <http://www.sublimetext.com/3>`__
.. |_pc| replace:: `Package Control <https://sublime.wbond.net/installation>`__
.. |_group| replace:: `SublimeLinter issue tracker <https://github.com/SublimeLinter/SublimeLinter3/issues>`__
.. |_cmd| replace:: `Command Palette <http://docs.sublimetext.info/en/sublime-text-3/extensibility/command_palette.html>`__
.. |_fnmatch| replace:: python’s `fnmatch method <http://docs.python.org/3/library/fnmatch.html>`__

.. role:: raw-html(raw)
   :format: html

.. |sp| unicode:: 0xA0
   :trim:

.. |bar_sep| replace:: |sp| |sp| | |sp| |sp|

.. |check| unicode:: 0x2713
   :trim:

.. |smiley| unicode:: 0x263A
