name: flake8

on:
  schedule:
    # flake8 regularly has breaking changes, so we re-check
    # regularly as well.
    - cron:  '0 9 * * 1'

  push:
    branches:
      - master
    paths:
    - 'setup.cfg'
    - '**.py'
    - '!docs/**'

  pull_request:
    paths:
    - 'setup.cfg'
    - '**.py'
    - '!docs/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Update pip and install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-docstrings
        echo '::add-matcher::'$PWD/.github/python-matcher.json
    - name: Lint with flake8
      run: |
        flake8 .
