name: flake8

on:
  push:
    paths:
    - '*.py'
    - 'setup.cfg'
  pull_request:
    paths:
    - '*.py'
    - 'setup.cfg'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Update pip and install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-docstrings
    - name: Lint with flake8
      run: |
        flake8 .
