name: flake8

on:
  schedule:
    # flake8 regularly has breaking changes, so we re-check
    # regularly as well.
    - cron:  '0 9 * * 1'

  push:
    branches:
      - master
    paths:
    - 'setup.cfg'
    - '**.py'
    - '!docs/**'

  pull_request:
    paths:
    - 'setup.cfg'
    - '**.py'
    - '!docs/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install "flake8<6.0.0"
    - uses: TrueBrain/actions-flake8@v2
